from typing import final

@final
class AllRegisterSnapshot:
    def reg(self, /, name: str) -> OneRegisterSnapshot |None: ...
    @property
    def time(self, /) -> int: ...

@final
class FrinetDb:
    def memory_bytes_at(self, /, time: int, addr: int, len: int) -> list[int |None]: ...
    def memory_reads(self, /, time: int, addr_range: tuple[int, int]) -> list[MemNode]: ...
    def memory_writes(self, /, time: int, addr_range: tuple[int, int]) -> list[MemNode]: ...
    @property
    def metadata(self, /) -> Metadata: ...
    def next_mem_read(self, /, time: int, addr_range: tuple[int, int]) -> int |None: ...
    def next_mem_write(self, /, time: int, addr_range: tuple[int, int]) -> int |None: ...
    def prev_mem_read(self, /, time: int, addr_range: tuple[int, int]) -> int |None: ...
    def prev_mem_write(self, /, time: int, addr_range: tuple[int, int]) -> int |None: ...
    def register(self, /, name: str) -> RegisterDb |None: ...
    def registers_snapshot(self, /, time: int) -> AllRegisterSnapshot: ...
    def search(self, /, text: str, regex: bool) -> list[SearchResult]: ...

@final
class MemNode:
    @property
    def addr_max(self, /) -> int: ...
    @property
    def addr_min(self, /) -> int: ...
    @property
    def time_max(self, /) -> int: ...
    @property
    def time_min(self, /) -> int: ...

@final
class Metadata:
    @property
    def alsr_slide(self, /) -> int |None: ...
    @property
    def register_names(self, /) -> list[str]: ...

@final
class OneRegisterSnapshot:
    @property
    def has_just_changed(self, /) -> bool: ...
    @property
    def next_time(self, /) -> int |None: ...
    @property
    def prev_time(self, /) -> int |None: ...
    @property
    def value(self, /) -> int |None: ...

@final
class RegisterDb:
    def first_time_with(self, /, value: int) -> int |None: ...
    def last_time_with(self, /, value: int) -> int |None: ...
    def next_time_with(self, /, time: int, value: int) -> int |None: ...
    def prev_time_with(self, /, time: int, value: int) -> int |None: ...
    def time_bbox(self, /) -> tuple[int, int]: ...
    def value_at(self, /, time: int) -> int |None: ...

@final
class SearchResult:
    @property
    def addr_max(self, /) -> int: ...
    @property
    def addr_min(self, /) -> int: ...
    @property
    def time_max(self, /) -> int: ...
    @property
    def time_min(self, /) -> int: ...

def open(path: str) -> FrinetDb: ...

